# Generated by Django 5.1.6 on 2025-02-09 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0002_remove_relationship_streak_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
