# Generated by Django 5.1.1 on 2025-02-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0003_alter_relationship_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='comprehension',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='curiosity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='empathy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='learn_from_you',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='learn_more',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='miracle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
