# Generated by Django 5.1.1 on 2025-02-10 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_remove_finances_update_alter_finances_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='finances',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='create',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
